--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ACM-PocketMine-MP/ScoreFactory
build-by-default: true
branches:
- PM5
projects:
  ScoreFactory:
    path: ""
    model: virion
    type: library
...
